/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'cpu' in SOPC Builder design 'eth_std_main_system'
 * SOPC Builder design path: ../../eth_std_main_system.sopcinfo
 *
 * Generated: Thu Nov 08 11:39:16 BRST 2018
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_qsys"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x8000820
#define ALT_CPU_CPU_FREQ 62500000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1d
#define ALT_CPU_DCACHE_LINE_SIZE 32
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_DCACHE_SIZE 32768
#define ALT_CPU_EXCEPTION_ADDR 0x10000120
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 62500000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 1
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 32768
#define ALT_CPU_INITDA_SUPPORTED
#define ALT_CPU_INST_ADDR_WIDTH 0x1d
#define ALT_CPU_NAME "cpu"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 0
#define ALT_CPU_RESET_ADDR 0x0


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x8000820
#define NIOS2_CPU_FREQ 62500000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0x1d
#define NIOS2_DCACHE_LINE_SIZE 32
#define NIOS2_DCACHE_LINE_SIZE_LOG2 5
#define NIOS2_DCACHE_SIZE 32768
#define NIOS2_EXCEPTION_ADDR 0x10000120
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 1
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 32768
#define NIOS2_INITDA_SUPPORTED
#define NIOS2_INST_ADDR_WIDTH 0x1d
#define NIOS2_NUM_OF_SHADOW_REG_SETS 0
#define NIOS2_RESET_ADDR 0x0


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PERFORMANCE_COUNTER
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SGDMA
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_AVALON_TIMER
#define __ALTERA_GENERIC_TRISTATE_CONTROLLER
#define __ALTERA_NIOS2_QSYS
#define __ALTMEMDDR2
#define __TRIPLE_SPEED_ETHERNET


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone III"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/peripheral_subsystem_jtag_uart"
#define ALT_STDERR_BASE 0x80000a8
#define ALT_STDERR_DEV peripheral_subsystem_jtag_uart
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/peripheral_subsystem_jtag_uart"
#define ALT_STDIN_BASE 0x80000a8
#define ALT_STDIN_DEV peripheral_subsystem_jtag_uart
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/peripheral_subsystem_jtag_uart"
#define ALT_STDOUT_BASE 0x80000a8
#define ALT_STDOUT_DEV peripheral_subsystem_jtag_uart
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "eth_std_main_system"


/*
 * ethernet_subsystem_descriptor_memory configuration
 *
 */

#define ALT_MODULE_CLASS_ethernet_subsystem_descriptor_memory altera_avalon_onchip_memory2
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_BASE 0x800c000
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_CONTENTS_INFO ""
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_DUAL_PORT 1
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_GUI_RAM_BLOCK_TYPE "Automatic"
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_INIT_CONTENTS_FILE "descriptor_memory"
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_INIT_MEM_CONTENT 1
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_INSTANCE_ID "NONE"
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_IRQ -1
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_NAME "/dev/ethernet_subsystem_descriptor_memory"
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_RAM_BLOCK_TYPE "Auto"
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_SINGLE_CLOCK_OP 0
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_SIZE_MULTIPLE 1
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_SIZE_VALUE 8192u
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_SPAN 8192
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define ETHERNET_SUBSYSTEM_DESCRIPTOR_MEMORY_WRITABLE 1


/*
 * ethernet_subsystem_sgdma_rx configuration
 *
 */

#define ALT_MODULE_CLASS_ethernet_subsystem_sgdma_rx altera_avalon_sgdma
#define ETHERNET_SUBSYSTEM_SGDMA_RX_ADDRESS_WIDTH 32
#define ETHERNET_SUBSYSTEM_SGDMA_RX_ALWAYS_DO_MAX_BURST 1
#define ETHERNET_SUBSYSTEM_SGDMA_RX_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define ETHERNET_SUBSYSTEM_SGDMA_RX_AVALON_MM_BYTE_REORDER_MODE 0
#define ETHERNET_SUBSYSTEM_SGDMA_RX_BASE 0x800a400
#define ETHERNET_SUBSYSTEM_SGDMA_RX_BURST_DATA_WIDTH 8
#define ETHERNET_SUBSYSTEM_SGDMA_RX_BURST_TRANSFER 0
#define ETHERNET_SUBSYSTEM_SGDMA_RX_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define ETHERNET_SUBSYSTEM_SGDMA_RX_CHAIN_WRITEBACK_DATA_WIDTH 32
#define ETHERNET_SUBSYSTEM_SGDMA_RX_COMMAND_FIFO_DATA_WIDTH 104
#define ETHERNET_SUBSYSTEM_SGDMA_RX_CONTROL_DATA_WIDTH 8
#define ETHERNET_SUBSYSTEM_SGDMA_RX_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define ETHERNET_SUBSYSTEM_SGDMA_RX_CONTROL_SLAVE_DATA_WIDTH 32
#define ETHERNET_SUBSYSTEM_SGDMA_RX_DESCRIPTOR_READ_BURST 0
#define ETHERNET_SUBSYSTEM_SGDMA_RX_DESC_DATA_WIDTH 32
#define ETHERNET_SUBSYSTEM_SGDMA_RX_HAS_READ_BLOCK 0
#define ETHERNET_SUBSYSTEM_SGDMA_RX_HAS_WRITE_BLOCK 1
#define ETHERNET_SUBSYSTEM_SGDMA_RX_IN_ERROR_WIDTH 6
#define ETHERNET_SUBSYSTEM_SGDMA_RX_IRQ 1
#define ETHERNET_SUBSYSTEM_SGDMA_RX_IRQ_INTERRUPT_CONTROLLER_ID 0
#define ETHERNET_SUBSYSTEM_SGDMA_RX_NAME "/dev/ethernet_subsystem_sgdma_rx"
#define ETHERNET_SUBSYSTEM_SGDMA_RX_OUT_ERROR_WIDTH 0
#define ETHERNET_SUBSYSTEM_SGDMA_RX_READ_BLOCK_DATA_WIDTH 32
#define ETHERNET_SUBSYSTEM_SGDMA_RX_READ_BURSTCOUNT_WIDTH 4
#define ETHERNET_SUBSYSTEM_SGDMA_RX_SPAN 64
#define ETHERNET_SUBSYSTEM_SGDMA_RX_STATUS_TOKEN_DATA_WIDTH 24
#define ETHERNET_SUBSYSTEM_SGDMA_RX_STREAM_DATA_WIDTH 32
#define ETHERNET_SUBSYSTEM_SGDMA_RX_SYMBOLS_PER_BEAT 4
#define ETHERNET_SUBSYSTEM_SGDMA_RX_TYPE "altera_avalon_sgdma"
#define ETHERNET_SUBSYSTEM_SGDMA_RX_UNALIGNED_TRANSFER 0
#define ETHERNET_SUBSYSTEM_SGDMA_RX_WRITE_BLOCK_DATA_WIDTH 32
#define ETHERNET_SUBSYSTEM_SGDMA_RX_WRITE_BURSTCOUNT_WIDTH 4


/*
 * ethernet_subsystem_sgdma_tx configuration
 *
 */

#define ALT_MODULE_CLASS_ethernet_subsystem_sgdma_tx altera_avalon_sgdma
#define ETHERNET_SUBSYSTEM_SGDMA_TX_ADDRESS_WIDTH 32
#define ETHERNET_SUBSYSTEM_SGDMA_TX_ALWAYS_DO_MAX_BURST 1
#define ETHERNET_SUBSYSTEM_SGDMA_TX_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define ETHERNET_SUBSYSTEM_SGDMA_TX_AVALON_MM_BYTE_REORDER_MODE 0
#define ETHERNET_SUBSYSTEM_SGDMA_TX_BASE 0x800a440
#define ETHERNET_SUBSYSTEM_SGDMA_TX_BURST_DATA_WIDTH 8
#define ETHERNET_SUBSYSTEM_SGDMA_TX_BURST_TRANSFER 0
#define ETHERNET_SUBSYSTEM_SGDMA_TX_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define ETHERNET_SUBSYSTEM_SGDMA_TX_CHAIN_WRITEBACK_DATA_WIDTH 32
#define ETHERNET_SUBSYSTEM_SGDMA_TX_COMMAND_FIFO_DATA_WIDTH 104
#define ETHERNET_SUBSYSTEM_SGDMA_TX_CONTROL_DATA_WIDTH 8
#define ETHERNET_SUBSYSTEM_SGDMA_TX_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define ETHERNET_SUBSYSTEM_SGDMA_TX_CONTROL_SLAVE_DATA_WIDTH 32
#define ETHERNET_SUBSYSTEM_SGDMA_TX_DESCRIPTOR_READ_BURST 0
#define ETHERNET_SUBSYSTEM_SGDMA_TX_DESC_DATA_WIDTH 32
#define ETHERNET_SUBSYSTEM_SGDMA_TX_HAS_READ_BLOCK 1
#define ETHERNET_SUBSYSTEM_SGDMA_TX_HAS_WRITE_BLOCK 0
#define ETHERNET_SUBSYSTEM_SGDMA_TX_IN_ERROR_WIDTH 0
#define ETHERNET_SUBSYSTEM_SGDMA_TX_IRQ 0
#define ETHERNET_SUBSYSTEM_SGDMA_TX_IRQ_INTERRUPT_CONTROLLER_ID 0
#define ETHERNET_SUBSYSTEM_SGDMA_TX_NAME "/dev/ethernet_subsystem_sgdma_tx"
#define ETHERNET_SUBSYSTEM_SGDMA_TX_OUT_ERROR_WIDTH 1
#define ETHERNET_SUBSYSTEM_SGDMA_TX_READ_BLOCK_DATA_WIDTH 32
#define ETHERNET_SUBSYSTEM_SGDMA_TX_READ_BURSTCOUNT_WIDTH 4
#define ETHERNET_SUBSYSTEM_SGDMA_TX_SPAN 64
#define ETHERNET_SUBSYSTEM_SGDMA_TX_STATUS_TOKEN_DATA_WIDTH 24
#define ETHERNET_SUBSYSTEM_SGDMA_TX_STREAM_DATA_WIDTH 32
#define ETHERNET_SUBSYSTEM_SGDMA_TX_SYMBOLS_PER_BEAT 4
#define ETHERNET_SUBSYSTEM_SGDMA_TX_TYPE "altera_avalon_sgdma"
#define ETHERNET_SUBSYSTEM_SGDMA_TX_UNALIGNED_TRANSFER 0
#define ETHERNET_SUBSYSTEM_SGDMA_TX_WRITE_BLOCK_DATA_WIDTH 32
#define ETHERNET_SUBSYSTEM_SGDMA_TX_WRITE_BURSTCOUNT_WIDTH 4


/*
 * ethernet_subsystem_tse_mac configuration
 *
 */

#define ALT_MODULE_CLASS_ethernet_subsystem_tse_mac triple_speed_ethernet
#define ETHERNET_SUBSYSTEM_TSE_MAC_BASE 0x800a000
#define ETHERNET_SUBSYSTEM_TSE_MAC_ENABLE_MACLITE 0
#define ETHERNET_SUBSYSTEM_TSE_MAC_FIFO_WIDTH 32
#define ETHERNET_SUBSYSTEM_TSE_MAC_IRQ -1
#define ETHERNET_SUBSYSTEM_TSE_MAC_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ETHERNET_SUBSYSTEM_TSE_MAC_IS_MULTICHANNEL_MAC 0
#define ETHERNET_SUBSYSTEM_TSE_MAC_MACLITE_GIGE 0
#define ETHERNET_SUBSYSTEM_TSE_MAC_MDIO_SHARED 0
#define ETHERNET_SUBSYSTEM_TSE_MAC_NAME "/dev/ethernet_subsystem_tse_mac"
#define ETHERNET_SUBSYSTEM_TSE_MAC_NUMBER_OF_CHANNEL 1
#define ETHERNET_SUBSYSTEM_TSE_MAC_NUMBER_OF_MAC_MDIO_SHARED 1
#define ETHERNET_SUBSYSTEM_TSE_MAC_PCS 0
#define ETHERNET_SUBSYSTEM_TSE_MAC_PCS_ID 0u
#define ETHERNET_SUBSYSTEM_TSE_MAC_PCS_SGMII 0
#define ETHERNET_SUBSYSTEM_TSE_MAC_RECEIVE_FIFO_DEPTH 2048
#define ETHERNET_SUBSYSTEM_TSE_MAC_REGISTER_SHARED 0
#define ETHERNET_SUBSYSTEM_TSE_MAC_RGMII 1
#define ETHERNET_SUBSYSTEM_TSE_MAC_SPAN 1024
#define ETHERNET_SUBSYSTEM_TSE_MAC_TRANSMIT_FIFO_DEPTH 2048
#define ETHERNET_SUBSYSTEM_TSE_MAC_TYPE "triple_speed_ethernet"
#define ETHERNET_SUBSYSTEM_TSE_MAC_UNASSIGNED "unassigned"
#define ETHERNET_SUBSYSTEM_TSE_MAC_USE_MDIO 1


/*
 * ext_flash configuration
 *
 */

#define ALT_MODULE_CLASS_ext_flash altera_generic_tristate_controller
#define EXT_FLASH_BASE 0x0
#define EXT_FLASH_HOLD_VALUE 1
#define EXT_FLASH_IRQ -1
#define EXT_FLASH_IRQ_INTERRUPT_CONTROLLER_ID -1
#define EXT_FLASH_NAME "/dev/ext_flash"
#define EXT_FLASH_SETUP_VALUE 75
#define EXT_FLASH_SIZE 67108864u
#define EXT_FLASH_SPAN 67108864
#define EXT_FLASH_TIMING_UNITS "ns"
#define EXT_FLASH_TYPE "altera_generic_tristate_controller"
#define EXT_FLASH_WAIT_VALUE 35


/*
 * hal configuration
 *
 */

#define ALT_MAX_FD 32
#define ALT_SYS_CLK PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER
#define ALT_TIMESTAMP_CLK none


/*
 * peripheral_subsystem_button_pio configuration
 *
 */

#define ALT_MODULE_CLASS_peripheral_subsystem_button_pio altera_avalon_pio
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_BASE 0x8000080
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_CAPTURE 1
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_DATA_WIDTH 4
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_DO_TEST_BENCH_WIRING 0
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_DRIVEN_SIM_VALUE 0x3
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_EDGE_TYPE "ANY"
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_FREQ 62500000u
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_HAS_IN 1
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_HAS_OUT 0
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_HAS_TRI 0
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_IRQ 4
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_IRQ_INTERRUPT_CONTROLLER_ID 0
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_IRQ_TYPE "EDGE"
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_NAME "/dev/peripheral_subsystem_button_pio"
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_RESET_VALUE 0x0
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_SPAN 16
#define PERIPHERAL_SUBSYSTEM_BUTTON_PIO_TYPE "altera_avalon_pio"


/*
 * peripheral_subsystem_high_res_timer configuration
 *
 */

#define ALT_MODULE_CLASS_peripheral_subsystem_high_res_timer altera_avalon_timer
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_ALWAYS_RUN 0
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_BASE 0x8000060
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_COUNTER_SIZE 32
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_FIXED_PERIOD 0
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_FREQ 62500000u
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_IRQ 3
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_LOAD_VALUE 624ull
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_MULT 1.0E-6
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_NAME "/dev/peripheral_subsystem_high_res_timer"
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_PERIOD 10.0
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_PERIOD_UNITS "us"
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_RESET_OUTPUT 0
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_SNAPSHOT 1
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_SPAN 32
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_TICKS_PER_SEC 100000u
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_TIMEOUT_PULSE_OUTPUT 0
#define PERIPHERAL_SUBSYSTEM_HIGH_RES_TIMER_TYPE "altera_avalon_timer"


/*
 * peripheral_subsystem_jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_peripheral_subsystem_jtag_uart altera_avalon_jtag_uart
#define PERIPHERAL_SUBSYSTEM_JTAG_UART_BASE 0x80000a8
#define PERIPHERAL_SUBSYSTEM_JTAG_UART_IRQ 5
#define PERIPHERAL_SUBSYSTEM_JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define PERIPHERAL_SUBSYSTEM_JTAG_UART_NAME "/dev/peripheral_subsystem_jtag_uart"
#define PERIPHERAL_SUBSYSTEM_JTAG_UART_READ_DEPTH 64
#define PERIPHERAL_SUBSYSTEM_JTAG_UART_READ_THRESHOLD 8
#define PERIPHERAL_SUBSYSTEM_JTAG_UART_SPAN 8
#define PERIPHERAL_SUBSYSTEM_JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define PERIPHERAL_SUBSYSTEM_JTAG_UART_WRITE_DEPTH 64
#define PERIPHERAL_SUBSYSTEM_JTAG_UART_WRITE_THRESHOLD 8


/*
 * peripheral_subsystem_led_pio configuration
 *
 */

#define ALT_MODULE_CLASS_peripheral_subsystem_led_pio altera_avalon_pio
#define PERIPHERAL_SUBSYSTEM_LED_PIO_BASE 0x8000090
#define PERIPHERAL_SUBSYSTEM_LED_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define PERIPHERAL_SUBSYSTEM_LED_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PERIPHERAL_SUBSYSTEM_LED_PIO_CAPTURE 0
#define PERIPHERAL_SUBSYSTEM_LED_PIO_DATA_WIDTH 8
#define PERIPHERAL_SUBSYSTEM_LED_PIO_DO_TEST_BENCH_WIRING 0
#define PERIPHERAL_SUBSYSTEM_LED_PIO_DRIVEN_SIM_VALUE 0x0
#define PERIPHERAL_SUBSYSTEM_LED_PIO_EDGE_TYPE "NONE"
#define PERIPHERAL_SUBSYSTEM_LED_PIO_FREQ 62500000u
#define PERIPHERAL_SUBSYSTEM_LED_PIO_HAS_IN 0
#define PERIPHERAL_SUBSYSTEM_LED_PIO_HAS_OUT 1
#define PERIPHERAL_SUBSYSTEM_LED_PIO_HAS_TRI 0
#define PERIPHERAL_SUBSYSTEM_LED_PIO_IRQ -1
#define PERIPHERAL_SUBSYSTEM_LED_PIO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PERIPHERAL_SUBSYSTEM_LED_PIO_IRQ_TYPE "NONE"
#define PERIPHERAL_SUBSYSTEM_LED_PIO_NAME "/dev/peripheral_subsystem_led_pio"
#define PERIPHERAL_SUBSYSTEM_LED_PIO_RESET_VALUE 0xaa
#define PERIPHERAL_SUBSYSTEM_LED_PIO_SPAN 16
#define PERIPHERAL_SUBSYSTEM_LED_PIO_TYPE "altera_avalon_pio"


/*
 * peripheral_subsystem_performance_counter configuration
 *
 */

#define ALT_MODULE_CLASS_peripheral_subsystem_performance_counter altera_avalon_performance_counter
#define PERIPHERAL_SUBSYSTEM_PERFORMANCE_COUNTER_BASE 0x8000000
#define PERIPHERAL_SUBSYSTEM_PERFORMANCE_COUNTER_HOW_MANY_SECTIONS 3
#define PERIPHERAL_SUBSYSTEM_PERFORMANCE_COUNTER_IRQ -1
#define PERIPHERAL_SUBSYSTEM_PERFORMANCE_COUNTER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PERIPHERAL_SUBSYSTEM_PERFORMANCE_COUNTER_NAME "/dev/peripheral_subsystem_performance_counter"
#define PERIPHERAL_SUBSYSTEM_PERFORMANCE_COUNTER_SPAN 64
#define PERIPHERAL_SUBSYSTEM_PERFORMANCE_COUNTER_TYPE "altera_avalon_performance_counter"


/*
 * peripheral_subsystem_pio_id_eeprom_dat configuration
 *
 */

#define ALT_MODULE_CLASS_peripheral_subsystem_pio_id_eeprom_dat altera_avalon_pio
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_BASE 0x80000b0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_BIT_CLEARING_EDGE_REGISTER 0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_CAPTURE 0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_DATA_WIDTH 1
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_DO_TEST_BENCH_WIRING 0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_DRIVEN_SIM_VALUE 0x0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_EDGE_TYPE "NONE"
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_FREQ 62500000u
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_HAS_IN 0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_HAS_OUT 0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_HAS_TRI 1
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_IRQ -1
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_IRQ_TYPE "NONE"
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_NAME "/dev/peripheral_subsystem_pio_id_eeprom_dat"
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_RESET_VALUE 0x0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_SPAN 16
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_DAT_TYPE "altera_avalon_pio"


/*
 * peripheral_subsystem_pio_id_eeprom_scl configuration
 *
 */

#define ALT_MODULE_CLASS_peripheral_subsystem_pio_id_eeprom_scl altera_avalon_pio
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_BASE 0x80000c0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_BIT_CLEARING_EDGE_REGISTER 0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_CAPTURE 0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_DATA_WIDTH 1
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_DO_TEST_BENCH_WIRING 0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_DRIVEN_SIM_VALUE 0x0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_EDGE_TYPE "NONE"
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_FREQ 62500000u
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_HAS_IN 0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_HAS_OUT 1
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_HAS_TRI 0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_IRQ -1
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_IRQ_TYPE "NONE"
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_NAME "/dev/peripheral_subsystem_pio_id_eeprom_scl"
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_RESET_VALUE 0x0
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_SPAN 16
#define PERIPHERAL_SUBSYSTEM_PIO_ID_EEPROM_SCL_TYPE "altera_avalon_pio"


/*
 * peripheral_subsystem_sys_clk_timer configuration
 *
 */

#define ALT_MODULE_CLASS_peripheral_subsystem_sys_clk_timer altera_avalon_timer
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_ALWAYS_RUN 0
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_BASE 0x8000040
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_COUNTER_SIZE 32
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_FIXED_PERIOD 0
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_FREQ 62500000u
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_IRQ 2
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_LOAD_VALUE 624999ull
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_MULT 0.0010
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_NAME "/dev/peripheral_subsystem_sys_clk_timer"
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_PERIOD 10.0
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_PERIOD_UNITS "ms"
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_RESET_OUTPUT 0
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_SNAPSHOT 1
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_SPAN 32
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_TICKS_PER_SEC 100u
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_TIMEOUT_PULSE_OUTPUT 0
#define PERIPHERAL_SUBSYSTEM_SYS_CLK_TIMER_TYPE "altera_avalon_timer"


/*
 * sdram configuration
 *
 */

#define ALT_MODULE_CLASS_sdram altmemddr2
#define SDRAM_BASE 0x10000000
#define SDRAM_IRQ -1
#define SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_NAME "/dev/sdram"
#define SDRAM_SPAN 33554432
#define SDRAM_TYPE "altmemddr2"


/*
 * sdram configuration as viewed by ethernet_subsystem_sgdma_rx_m_write
 *
 */

#define ETHERNET_SUBSYSTEM_SGDMA_RX_M_WRITE_SDRAM_BASE 0x10000000
#define ETHERNET_SUBSYSTEM_SGDMA_RX_M_WRITE_SDRAM_IRQ -1
#define ETHERNET_SUBSYSTEM_SGDMA_RX_M_WRITE_SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ETHERNET_SUBSYSTEM_SGDMA_RX_M_WRITE_SDRAM_NAME "/dev/sdram"
#define ETHERNET_SUBSYSTEM_SGDMA_RX_M_WRITE_SDRAM_SPAN 33554432
#define ETHERNET_SUBSYSTEM_SGDMA_RX_M_WRITE_SDRAM_TYPE "altmemddr2"


/*
 * sdram configuration as viewed by ethernet_subsystem_sgdma_tx_m_read
 *
 */

#define ETHERNET_SUBSYSTEM_SGDMA_TX_M_READ_SDRAM_BASE 0x10000000
#define ETHERNET_SUBSYSTEM_SGDMA_TX_M_READ_SDRAM_IRQ -1
#define ETHERNET_SUBSYSTEM_SGDMA_TX_M_READ_SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ETHERNET_SUBSYSTEM_SGDMA_TX_M_READ_SDRAM_NAME "/dev/sdram"
#define ETHERNET_SUBSYSTEM_SGDMA_TX_M_READ_SDRAM_SPAN 33554432
#define ETHERNET_SUBSYSTEM_SGDMA_TX_M_READ_SDRAM_TYPE "altmemddr2"


/*
 * sysid configuration
 *
 */

#define ALT_MODULE_CLASS_sysid altera_avalon_sysid_qsys
#define SYSID_BASE 0x800e000
#define SYSID_ID 0
#define SYSID_IRQ -1
#define SYSID_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_NAME "/dev/sysid"
#define SYSID_SPAN 8
#define SYSID_TIMESTAMP 1344838623
#define SYSID_TYPE "altera_avalon_sysid_qsys"

#endif /* __SYSTEM_H_ */
